project:
  type: website
  output-dir: public

website:
  title: "MAVEX"
  navbar:
    left:
      - href: engg/index.qmd
        text: engg
      - href: inventory/index.qmd
        text: inventory
      - href: learning/index.qmd
        text: learning
      - href: operations/index.qmd
        text: ops
      - href: erc/index.qmd
        text: "erc"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-depth: 6
