---
default:
# The Docker image that will be used to build your app
  image: ghcr.io/quarto-dev/quarto:1.10.3
  # Functions that should be executed before the build script is run
  before_script:
    - ls

workflow:
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

create-pages:
  stage: deploy
  script:
    - cd website
    - quarto render
    - mv ../public
  pages: true
    # The folder that contains the files to be exposed at the Page URL
    #publish: website/public
