project:
  type: website
  output-dir: public

website:
  title: "MAVEX"
  navbar:
    left:
      - href: bill-of-materials.qmd
        text: BoM
      - href: 2026/procurement.qmd
        text: "2026"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
