project:
  type: website
  output-dir: public

website:
  title: "MAVEX"
  navbar:
    left:
      - href: inventory/index.qmd
        text: Inventory
      - href: learning/index.qmd
        text: Learning
      - href: 2026/index.qmd
        text: "2026"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-depth: 6
